### ISSUE TITLE
Pymt_Sedflux—What's the maximum and minimum value of all the variables in sedflux model? 

### ISSUE THREAD

**Issue by XianaZhang** [mcflugen/sedflux#11] opened 2020-04-15 01:55 UTC
@mcflugen Hi there,
I wonder if there is range for the maximum and minimum value of the bed-load grain size and other variables? For example, because i saw there is a file named parameters.yaml in the template input files for sedflux 3d as seen below, there is a maximum and minimum value defined and i just always thought that means a range for the bed-load grain size value. Does this thought correct? What's the real meaning of them?
bed_load_sediment_grain_size:
description: Grain size of bed-load sediment
value:
default: 400.0
range:
max: 5000.0
min: 0.1
type: float
units: um
I also want to know is there an upper limit for the number of sediment grain types, seasons for river and epoches?
And there are some other input variables which are not mentioned in sedflux documentation, for example the variable 'channel_exit_x-section_mean_of_depth'. Because there are also the variable 'depth' in river file, i just don't know what's the relationship of them. If the delta morphology is more controled by the 'channel_exit_x-section_mean_of_depth' than 'depth' which is defined in river file ? And also what's the maximum and minimum value for these 'other input variables'?
Except the questions above, i also have my last two questions. I feel confused by the plum process file. I saw there is a description for it in the sedflux documents as seen below. Does that mean if i want to run plum model alone, i need to download the two files? And if i just run the sedflux3d model, Does i also need to download them ?
To run the plume model you will need two input files. I’ve create an example of each to get you started:
plume_config.kvf: describes some physical and numerical constants used by the model.
plume_flood.kvf: describes input conditions to the model.
And there is a function named model.parameters. I wonder what it works for? Because it seems that it's output is the variables and their values of the template input files, not the new input files which we created by setup functions and have changed the values and variables for them by manule.

**Comment by mcflugen** [comment] 2020-04-16 05:18
Duplicate of csdms/help-desk#22.

**Closed as completed by mcflugen** 2020-04-16 05:18 UTC
Labels: duplicate
